!> \file
!> \author Chris Bradley
!> \brief This module contains all constraint conditions operators routines.
!>
!> \section LICENSE
!>
!> Version: MPL 1.1/GPL 2.0/LGPL 2.1
!>
!> The contents of this file are subject to the Mozilla Public License
!> Version 1.1 (the "License"); you may not use this file except in
!> compliance with the License. You may obtain a copy of the License at
!> http://www.mozilla.org/MPL/
!>
!> Software distributed under the License is distributed on an "AS IS"
!> basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
!> License for the specific language governing rights and limitations
!> under the License.
!>
!> The Original Code is OpenCMISS
!>
!> The Initial Developer of the Original Code is University of Auckland,
!> Auckland, New Zealand, the University of Oxford, Oxford, United
!> Kingdom and King's College, London, United Kingdom. Portions created
!> by the University of Auckland, the University of Oxford and King's
!> College, London are Copyright (C) 2007-2010 by the University of
!> Auckland, the University of Oxford and King's College, London.
!> All Rights Reserved.
!>
!> Contributor(s): Sander Arens 
!>
!> Alternatively, the contents of this file may be used under the terms of
!> either the GNU General Public License Version 2 or later (the "GPL"), or
!> the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
!> in which case the provisions of the GPL or the LGPL are applicable instead
!> of those above. If you wish to allow use of your version of this file only
!> under the terms of either the GPL or the LGPL, and not to allow others to
!> use your version of this file under the terms of the MPL, indicate your
!> decision by deleting the provisions above and replace them with the notice
!> and other provisions required by the GPL or the LGPL. If you do not delete
!> the provisions above, a recipient may use your version of this file under
!> the terms of any one of the MPL, the GPL or the LGPL.
!>

!>This module contains all constraint conditions routines. 
MODULE CONSTRAINT_OPERATORS_ROUTINES

  USE BASE_ROUTINES
  USE BASIS_ROUTINES
  USE CONSTANTS
  USE FIELD_ROUTINES
  USE INPUT_OUTPUT
  USE CONSTRAINT_CONDITIONS_CONSTANTS
  USE CONSTRAINT_EQUATIONS_ROUTINES
  USE CONSTRAINT_MAPPING_ROUTINES
  USE CONSTRAINT_MATRICES_ROUTINES
  USE ISO_VARYING_STRING
  USE KINDS
  USE MATRIX_VECTOR
  USE STRINGS
  USE TIMER
  USE TYPES

  IMPLICIT NONE

  !Module types

  !Module variables

  !Interfaces

  PUBLIC FE_INCOMPRESSIBILITY_FINITE_ELEMENT_JACOBIAN_EVALUATE
  PUBLIC FE_INCOMPRESSIBILITY_FINITE_ELEMENT_RESIDUAL_EVALUATE
  
CONTAINS

  !
  !================================================================================================================================
  !

  !>Evaluates the element Jacobian matrix for the given element number for a finite elasticity incompressibility constraint condition.
  SUBROUTINE FE_INCOMPRESSIBILITY_FINITE_ELEMENT_JACOBIAN_EVALUATE(CONSTRAINT_CONDITION,ELEMENT_NUMBER,ERR,ERROR,*)
    !Argument variables
    TYPE(CONSTRAINT_CONDITION_TYPE), POINTER :: CONSTRAINT_CONDITION !<A pointer to the constraint condition
    INTEGER(INTG), INTENT(IN) :: ELEMENT_NUMBER !<The element number to evaluate the Jacobian for
    INTEGER(INTG), INTENT(OUT) :: ERR !<The error code
    TYPE(VARYING_STRING), INTENT(OUT) :: ERROR !<The error string
    !Local Variables
    TYPE(VARYING_STRING) :: LOCAL_ERROR
    INTEGER(INTG) :: FIELD_VARIABLE_TYPE,LAGRANGE_VARIABLE_TYPE
    INTEGER(INTG) :: ng,nh,ns,nhs,ni,mh,ms,mhs,mi
    INTEGER(INTG) :: MESH_COMPONENT_NUMBER
    REAL(DP) :: JGW_DPHINS_DZ,PHIMS
    REAL(DP) :: JGW
    TYPE(BASIS_TYPE), POINTER :: GEOMETRIC_BASIS,DEPENDENT_BASIS,LAGRANGE_BASIS
    TYPE(CONSTRAINT_EQUATIONS_TYPE), POINTER :: CONSTRAINT_EQUATIONS
    TYPE(CONSTRAINT_EQUATIONS_MAPPING_TYPE), POINTER :: CONSTRAINT_MAPPING
    TYPE(CONSTRAINT_EQUATIONS_MAPPING_NONLINEAR_TYPE), POINTER :: NONLINEAR_MAPPING
    TYPE(CONSTRAINT_MATRICES_TYPE), POINTER :: CONSTRAINT_MATRICES
    TYPE(CONSTRAINT_MATRICES_NONLINEAR_TYPE), POINTER :: NONLINEAR_MATRICES
    TYPE(CONSTRAINT_EQUATIONS_JACOBIAN_TYPE), POINTER :: JACOBIAN_MATRIX
    TYPE(FIELD_INTERPOLATED_POINT_TYPE), POINTER :: GEOMETRIC_INTERPOLATED_POINT,DEPENDENT_INTERPOLATED_POINT, &
      & LAGRANGE_INTERPOLATED_POINT
    TYPE(FIELD_INTERPOLATED_POINT_METRICS_TYPE), POINTER :: GEOMETRIC_INTERPOLATED_POINT_METRICS, &
      & DEPENDENT_INTERPOLATED_POINT_METRICS
    TYPE(FIELD_INTERPOLATION_PARAMETERS_TYPE), POINTER :: GEOMETRIC_INTERPOLATION_PARAMETERS, &
      & DEPENDENT_INTERPOLATION_PARAMETERS,LAGRANGE_INTERPOLATION_PARAMETERS
    TYPE(FIELD_TYPE), POINTER :: GEOMETRIC_FIELD,DEPENDENT_FIELD,LAGRANGE_FIELD
    TYPE(FIELD_VARIABLE_TYPE), POINTER :: FIELD_VARIABLE,LAGRANGE_VARIABLE
    TYPE(QUADRATURE_SCHEME_TYPE), POINTER :: QUADRATURE_SCHEME,LAGRANGE_QUADRATURE_SCHEME

    CALL ENTERS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_JACOBIAN_EVALUATE",ERR,ERROR,*999)

    IF(ASSOCIATED(CONSTRAINT_CONDITION)) THEN
      CONSTRAINT_EQUATIONS=>CONSTRAINT_CONDITION%EQUATIONS
      IF(ASSOCIATED(CONSTRAINT_EQUATIONS)) THEN
        CONSTRAINT_MATRICES=>CONSTRAINT_EQUATIONS%CONSTRAINT_MATRICES
        NONLINEAR_MATRICES=>CONSTRAINT_MATRICES%NONLINEAR_MATRICES
        JACOBIAN_MATRIX=>NONLINEAR_MATRICES%JACOBIANS(JACOBIAN_NUMBER)%PTR
            IF(JACOBIAN_MATRIX%UPDATE_JACOBIAN) THEN
              LAGRANGE_FIELD=>CONSTRAINT_EQUATIONS%INTERPOLATION%LAGRANGE_FIELD
              GEOMETRIC_FIELD=>CONSTRAINT_EQUATIONS%INTERPOLATION%GEOMETRIC_FIELD
              MESH_COMPONENT_NUMBER=LAGRANGE_FIELD%DECOMPOSITION%MESH_COMPONENT_NUMBER
              LAGRANGE_BASIS=>LAGRANGE_FIELD%DECOMPOSITION%DOMAIN(LAGRANGE_FIELD%DECOMPOSITION%MESH_COMPONENT_NUMBER)%PTR% &
                & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
              QUADRATURE_SCHEME=>LAGRANGE_BASIS%QUADRATURE%QUADRATURE_SCHEME_MAP(BASIS_DEFAULT_QUADRATURE_SCHEME)%PTR
              CONSTRAINT_MAPPING=>CONSTRAINT_EQUATIONS%EQUATIONS_MAPPING
              NONLINEAR_MAPPING=>EQUATIONS_MAPPING%NONLINEAR_MAPPING
              LAGRANGE_VARIABLE_TYPE=>NONLINEAR_MAPPING%RESIDUAL_VARIABLES(1) !The hydrostatic pressure field variable.
              COUPLED_FIELD_VARIABLE=>NONLINEAR_MAPPING%JACOBIAN_TO_VAR_MAP(JACOBIAN_NUMBER)%VARIABLE !The deformed coordinate field variable.
              COUPLED_LAGRANGE_VARIABLE_TYPE=COUPLED_FIELD_VARIABLE%VARIABLE_TYPE
              COUPLED_LAGRANGE_INTERPOLATION_PARAMETERS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
                & LAGRANGE_INTERP_PARAMETERS(COUPLED_LAGRANGE_VARIABLE_TYPE)%PTR
              GEOMETRIC_INTERPOLATION_PARAMETERS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
                & LAGRANGE_INTERP_PARAMETERS(FIELD_U_VARIABLE_TYPE)%PTR
              CALL FIELD_INTERPOLATION_PARAMETERS_ELEMENT_GET(FIELD_VALUES_SET_TYPE,ELEMENT_NUMBER, &
                & COUPLED_LAGRANGE_INTERPOLATION_PARAMETERS,ERR,ERROR,*999)
              CALL FIELD_INTERPOLATION_PARAMETERS_ELEMENT_GET(FIELD_VALUES_SET_TYPE, &
                & GEOMETRIC_INTERPOLATION_PARAMETERS,ERR,ERROR,*999)
              GEOMETRIC_INTERPOLATED_POINT=>CONSTRAINT_EQUATIONS%INTERPOLATION%GEOMETRIC_INTERP_POINT(FIELD_U_VARIABLE_TYPE)%PTR
              GEOMETRIC_INTERPOLATED_POINT_METRICS=>CONSTRAINT_EQUATIONS%INTERPOLATION%GEOMETRIC_INTERP_POINT_METRICS(FIELD_U_VARIABLE_TYPE)%PTR
              COUPLED_LAGRANGE_INTERPOLATED_POINT=>CONSTRAINT_EQUATIONS%INTERPOLATION%LAGRANGE_INTERP_POINT(COUPLED_LAGRANGE_VARIABLE_TYPE)%PTR
              COUPLED_LAGRANGE_INTERPOLATED_POINT_METRICS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
                & LAGRANGE_INTERP_POINT_METRICS(COUPLED_LAGRANGE_VARIABLE_TYPE)%PTR
             
              !These do not change, as there is only one component for the hydrostatic pressure field variable.
              MESH_COMPONENT_NUMBER=FIELD_VARIABLE%COMPONENTS(1)%MESH_COMPONENT_NUMBER
              LAGRANGE_BASIS=>LAGRANGE_FIELD%DECOMPOSITION%DOMAIN(MESH_COMPONENT_NUMBER)%PTR% &
                & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
              QUADRATURE_SCHEME=>LAGRANGE_BASIS%QUADRATURE%QUADRATURE_SCHEME_MAP(BASIS_DEFAULT_QUADRATURE_SCHEME)%PTR

              !Loop over all Gauss points 
              DO ng=1,QUADRATURE_SCHEME%NUMBER_OF_GAUSS
                CALL FIELD_INTERPOLATE_GAUSS(FIRST_PART_DERIV,BASIS_DEFAULT_QUADRATURE_SCHEME,ng, &
                  & GEOMETRIC_INTERPOLATED_POINT,ERR,ERROR,*999)
                CALL FIELD_INTERPOLATED_POINT_METRICS_CALCULATE(COORDINATE_JACOBIAN_VOLUME_TYPE, &
                  & GEOMETRIC_INTERPOLATED_POINT_METRICS,ERR,ERROR,*999)
                CALL FIELD_INTERPOLATE_GAUSS(FIRST_PART_DERIV,BASIS_DEFAULT_QUADRATURE_SCHEME,ng, &
                  & COUPLED_LAGRANGE_INTERPOLATED_POINT,ERR,ERROR,*999)
                CALL FIELD_INTERPOLATED_POINT_METRICS_CALCULATE(COORDINATE_JACOBIAN_VOLUME_TYPE, &
                  & COUPLED_LAGRANGE_INTERPOLATED_POINT_METRICS,ERR,ERROR,*999)
                
                JGW=COUPLED_LAGRANGE_INTERPOLATED_POINT_METRICS%JACOBIAN*QUADRATURE_SCHEME%GAUSS_WEIGHTS(ng)

                nhs=0
                IF(FIELD_VARIABLE%COMPONENTS(1)%INTERPOLATION_TYPE==FIELD_NODE_BASED_INTERPOLATION) THEN !node based
                  DO nh=1,COUPLED_FIELD_VARIABLE%NUMBER_OF_COMPONENTS
                    MESH_COMPONENT_NUMBER=COUPLED_FIELD_VARIABLE%COMPONENTS(nh)%MESH_COMPONENT_NUMBER
                    COUPLED_LAGRANGE_BASIS=>COUPLED_LAGRANGE_FIELD%DECOMPOSITION%DOMAIN(MESH_COMPONENT_NUMBER)%PTR% &
                      & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
                    COUPLED_QUADRATURE_SCHEME=>COUPLED_LAGRANGE_BASIS%QUADRATURE% &
                      & QUADRATURE_SCHEME_MAP(BASIS_DEFAULT_QUADRATURE_SCHEME)%PTR
                    DO ns=1,COUPLED_LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                      DPHINS_DZ=0.0_DP
                      DO ni=1,COUPLED_LAGRANGE_BASIS%NUMBER_OF_XI
                        DPHINS_DZ=DPHINS_DZ+ &
                          & COUPLED_QUADRATURE_SCHEME%GAUSS_BASIS_FNS(ns,PARTIAL_DERIVATIVE_FIRST_DERIVATIVE_MAP(ni),ng)* &
                          & COUPLED_LAGRANGE_INTERPOLATED_POINT_METRICS%DXI_DX(ni,nh)
                      ENDDO !ni
                      JGW_DPHINS_DZ=JGW*DPHINS_DZ
                      nhs=nhs+1
                      mhs=0
                      DO ms=1,LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                        mhs=mhs+1
                        PHIMS=QUADRATURE_SCHEME%GAUSS_BASIS_FNS(ms,NO_PART_DERIV,ng)
                        JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)=JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)+ &
                          & JGW_DPHINS_DZ*PHIMS
                      ENDDO !ms    
                    ENDDO !ns
                  ENDDO !nh
                ELSEIF(FIELD_VARIABLE%COMPONENTS(1)%INTERPOLATION_TYPE==FIELD_ELEMENT_BASED_INTERPOLATION) THEN !element based
                  DO nh=1,COUPLED_FIELD_VARIABLE%NUMBER_OF_COMPONENTS
                    MESH_COMPONENT_NUMBER=COUPLED_FIELD_VARIABLE%COMPONENTS(nh)%MESH_COMPONENT_NUMBER
                    COUPLED_LAGRANGE_BASIS=>COUPLED_LAGRANGE_FIELD%DECOMPOSITION%DOMAIN(MESH_COMPONENT_NUMBER)%PTR% &
                      & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
                    COUPLED_QUADRATURE_SCHEME=>COUPLED_LAGRANGE_BASIS%QUADRATURE% &
                      & QUADRATURE_SCHEME_MAP(BASIS_DEFAULT_QUADRATURE_SCHEME)%PTR
                    DO ns=1,COUPLED_LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                      DPHINS_DZ=0.0_DP
                      DO ni=1,COUPLED_LAGRANGE_BASIS%NUMBER_OF_XI
                        DPHINS_DZ=DPHINS_DZ+ &
                          & COUPLED_QUADRATURE_SCHEME%GAUSS_BASIS_FNS(ns,PARTIAL_DERIVATIVE_FIRST_DERIVATIVE_MAP(ni),ng)* &
                          & COUPLED_LAGRANGE_INTERPOLATED_POINT_METRICS%DXI_DX(ni,nh)
                      ENDDO !ni
                      JGW_DPHINS_DZ=JGW*DPHINS_DZ
                      nhs=nhs+1
                      mhs=0
                      DO ms=1,LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                        mhs=mhs+1
                        JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)=JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)+ &
                          & JGW_DPHINS_DZ
                      ENDDO !ms    
                    ENDDO !ns
                  ENDDO !nh
                ENDIF
              ENDDO !ng

              !Scale factor adjustment
              !Rows correspond to dependent field variable, columns to lagrange field variable.
              IF(LAGRANGE_FIELD%SCALINGS%SCALING_TYPE/=FIELD_NO_SCALING) THEN
                CALL FIELD_INTERPOLATION_PARAMETERS_SCALE_FACTORS_ELEM_GET(ELEMENT_NUMBER, &
                  & LAGRANGE_INTERPOLATION_PARAMETERS,ERR,ERROR,*999) 
                CALL FIELD_INTERPOLATION_PARAMETERS_SCALE_FACTORS_ELEM_GET(ELEMENT_NUMBER, &
                  & COUPLED_LAGRANGE_INTERPOLATION_PARAMETERS,ERR,ERROR,*999) 
                nhs=0
                IF(FIELD_VARIABLE%COMPONENTS(1)%INTERPOLATION_TYPE==FIELD_NODE_BASED_INTERPOLATION) THEN !node based
                  DO nh=1,COUPLED_FIELD_VARIABLE%NUMBER_OF_COMPONENTS
                    MESH_COMPONENT_NUMBER=COUPLED_FIELD_VARIABLE%COMPONENTS(nh)%MESH_COMPONENT_NUMBER
                    COUPLED_LAGRANGE_BASIS=>COUPLED_LAGRANGE_FIELD%DECOMPOSITION%DOMAIN(MESH_COMPONENT_NUMBER)%PTR% &
                      & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
                    DO ns=1,COUPLED_LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                      nhs=nhs+1
                      mhs=0
                      DO ms=1,LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                        mhs=mhs+1
                        JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)=JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)* &
                          & LAGRANGE_INTERPOLATION_PARAMETERS%SCALE_FACTORS(ms,1)* &
                          & COUPLED_LAGRANGE_INTERPOLATION_PARAMETERS%SCALE_FACTORS(ns,nh)
                      ENDDO !ms    
                    ENDDO !ns
                  ENDDO !nh
                ELSEIF(FIELD_VARIABLE%COMPONENTS(1)%INTERPOLATION_TYPE==FIELD_ELEMENT_BASED_INTERPOLATION) THEN !element based
                  DO nh=1,COUPLED_FIELD_VARIABLE%NUMBER_OF_COMPONENTS
                    MESH_COMPONENT_NUMBER=COUPLED_FIELD_VARIABLE%COMPONENTS(nh)%MESH_COMPONENT_NUMBER
                    COUPLED_LAGRANGE_BASIS=>COUPLED_LAGRANGE_FIELD%DECOMPOSITION%DOMAIN(MESH_COMPONENT_NUMBER)%PTR% &
                      & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
                    DO ns=1,COUPLED_LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                      nhs=nhs+1
                      mhs=0
                      DO ms=1,LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                        mhs=mhs+1
                        JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)=JACOBIAN_MATRIX%ELEMENT_JACOBIAN%MATRIX(mhs,nhs)* &
                          & COUPLED_LAGRANGE_INTERPOLATION_PARAMETERS%SCALE_FACTORS(ns,nh)
                      ENDDO !ms    
                    ENDDO !ns
                  ENDDO !nh
                ENDIF
              ENDIF
            ENDIF
        ENDIF
      ELSE
        CALL FLAG_ERROR("Constraint condition equations is not associated.",ERR,ERROR,*999)
      ENDIF
    ELSE
      CALL FLAG_ERROR("Constraint condition is not associated.",ERR,ERROR,*999)
    ENDIF

    CALL EXITS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_JACOBIAN_EVALUATE")
    RETURN
999 CALL ERRORS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_JACOBIAN_EVALUATE",ERR,ERROR)
    CALL EXITS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_JACOBIAN_EVALUATE")
    RETURN 1
  END SUBROUTINE FE_INCOMPRESSIBILITY_FINITE_ELEMENT_JACOBIAN_EVALUATE

  !
  !================================================================================================================================
  !

  !>Evaluates the residual for a finite element finite elasticity incompressibility constraint condition.
  SUBROUTINE FE_INCOMPRESSIBILITY_FINITE_ELEMENT_RESIDUAL_EVALUATE(CONSTRAINT_CONDITION,ELEMENT_NUMBER,ERR,ERROR,*)

    !Argument variables
    TYPE(CONSTRAINT_CONDITION_TYPE), POINTER :: CONSTRAINT_CONDITION !<A pointer to the constraint condition
    INTEGER(INTG), INTENT(IN) :: ELEMENT_NUMBER !<The element number to calculate
    INTEGER(INTG), INTENT(OUT) :: ERR !<The error code
    TYPE(VARYING_STRING), INTENT(OUT) :: ERROR !<The error string
    !Local Variables
    TYPE(BASIS_TYPE), POINTER :: GEOMETRIC_BASIS,DEPENDENT_BASIS,LAGRANGE_BASIS
    TYPE(CONSTRAINT_EQUATIONS_TYPE), POINTER :: CONSTRAINT
    TYPE(CONSTRAINT_EQUATIONS_MAPPING_TYPE), POINTER :: CONSTRAINT_MAPPING
    TYPE(CONSTRAINT_MATRICES_TYPE), POINTER :: CONSTRAINT_MATRICES
    TYPE(CONSTRAINT_MATRICES_NONLINEAR_TYPE), POINTER :: NONLINEAR_MATRICES
    TYPE(FIELD_TYPE), POINTER :: GEOMETRIC_FIELD,DEPENDENT_FIELD,LAGRANGE_FIELD
    TYPE(FIELD_VARIABLE_TYPE), POINTER :: FIELD_VARIABLE,LAGRANGE_VARIABLE
    TYPE(QUADRATURE_SCHEME_TYPE), POINTER :: LAGRANGE_QUADRATURE_SCHEME
    TYPE(FIELD_INTERPOLATION_PARAMETERS_TYPE), POINTER :: GEOMETRIC_INTERPOLATION_PARAMETERS,DEPENDENT_INTERPOLATION_PARAMETERS, &
      & LAGRANGE_INTERPOLATION_PARAMETERS
    TYPE(FIELD_INTERPOLATED_POINT_TYPE), POINTER :: GEOMETRIC_INTERPOLATED_POINT,DEPENDENT_INTERPOLATED_POINT, &
      & LAGRANGE_INTERPOLATED_POINT
    TYPE(FIELD_INTERPOLATED_POINT_METRICS_TYPE), POINTER :: GEOMETRIC_INTERPOLATED_POINT_METRICS, &
      & DEPENDENT_INTERPOLATED_POINT_METRICS
    TYPE(DECOMPOSITION_TYPE), POINTER :: DECOMPOSITION
    INTEGER(INTG) :: parameter_idx,gauss_idx,element_dof_idx
    INTEGER(INTG) :: FIELD_VARIABLE_TYPE,LAGRANGE_VARIABLE_TYPE
    INTEGER(INTG) :: MESH_COMPONENT_NUMBER
    REAL(DP) :: JGW

    CALL ENTERS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_RESIDUAL_EVALUATE",ERR,ERROR,*999)

    NULLIFY(LAGRANGE_BASIS,COMPONENT_BASIS)
    NULLIFY(CONSTRAINT_EQUATIONS,EQUATIONS_MAPPING,CONSTRAINT_MATRICES,NONLINEAR_MATRICES)
    NULLIFY(DEPENDENT_FIELD,GEOMETRIC_FIELD,LAGRANGE_FIELD)
    NULLIFY(FIELD_VARIABLE,LAGRANGE_VARIABLE)
    NULLIFY(LAGRANGE_QUADRATURE_SCHEME)
    NULLIFY(GEOMETRIC_INTERPOLATION_PARAMETERS,DEPENDENT_INTERPOLATION_PARAMETERS,LAGRANGE_INTERPOLATION_PARAMETERS)
    NULLIFY(GEOMETRIC_INTERPOLATED_POINT,DEPENDENT_INTERPOLATED_POINT,LAGRANGE_INTERPOLATED_POINT)
    NULLIFY(GEOMETRIC_INTERPOLATED_POINT_METRICS,DEPENDENT,_INTERPOLATED_POINT_METRICS)
    NULLIFY(DECOMPOSITION)

    IF(ASSOCIATED(CONSTRAINT_CONDITION)) THEN
      CONSTRAINT_EQUATIONS=>CONSTRAINT_CONDITION%EQUATIONS
      IF(ASSOCIATED(CONSTRAINT_EQUATIONS)) THEN
        SELECT CASE(CONSTRAINT_CONDITION%METHOD)
        CASE(CONSTRAINT_CONDITION_LAGRANGE_MULTIPLIERS_METHOD)
          CONSTRAINT_MATRICES=>CONSTRAINT_EQUATIONS%CONSTRAINT_MATRICES
          NONLINEAR_MATRICES=>CONSTRAINT_MATRICES%NONLINEAR_MATRICES
          CONSTRAINT_MAPPING=>CONSTRAINT_EQUATIONS%EQUATIONS_MAPPING
          GEOMETRIC_FIELD=>CONSTRAINT_EQUATIONS%INTERPOLATION%GEOMETRIC_FIELD
          DEPENDENT_FIELD=>CONSTRAINT_EQUATIONS%INTERPOLATION%DEPENDENT_FIELD
          LAGRANGE_FIELD=>CONSTRAINT_EQUATIONS%INTERPOLATION%LAGRANGE_FIELD
          GEOMETRIC_BASIS=>GEOMETRIC_FIELD%DECOMPOSITION%DOMAIN(GEOMETRIC_FIELD%DECOMPOSITION%MESH_COMPONENT_NUMBER)%PTR% &
            & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
          DEPENDENT_BASIS=>DEPENDENT_FIELD%DECOMPOSITION%DOMAIN(DEPENDENT_FIELD%DECOMPOSITION%MESH_COMPONENT_NUMBER)%PTR% &
            & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
          MESH_COMPONENT_NUMBER=LAGRANGE_VARIABLE%COMPONENTS(1)%MESH_COMPONENT_NUMBER
          LAGRANGE_BASIS=>LAGRANGE_FIELD%DECOMPOSITION%DOMAIN(MESH_COMPONENT_NUMBER)%PTR% &
            & TOPOLOGY%ELEMENTS%ELEMENTS(ELEMENT_NUMBER)%BASIS
          LAGRANGE_QUADRATURE_SCHEME=>LAGRANGE_BASIS%QUADRATURE%QUADRATURE_SCHEME_MAP(BASIS_DEFAULT_QUADRATURE_SCHEME)%PTR
          FIELD_VARIABLE=>CONSTRAINT_EQUATIONS%CONSTRAINT_MAPPING%NONLINEAR_MAPPING%VARIABLE
          FIELD_VARIABLE_TYPE=FIELD_VARIABLE%VARIABLE_TYPE
          LAGRANGE_VARIABLE=>CONSTRAINT_EQUATIONS%CONSTRAINT_MAPPING%NONLINEAR_MAPPING%LAGRANGE_VARIABLE
          LAGRANGE_VARIABLE_TYPE=LAGRANGE_FIELD_VARIABLE%VARIABLE_TYPE
          GEOMETRIC_INTERPOLATION_PARAMETERS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
            & GEOMETRIC_INTERP_PARAMETERS(FIELD_U_VARIABLE_TYPE)%PTR
          DEPENDENT_INTERPOLATION_PARAMETERS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
            & DEPENDENT_INTERP_PARAMETERS(FIELD_VARIABLE_TYPE)%PTR
          LAGRANGE_INTERPOLATION_PARAMETERS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
            & DEPENDENT_INTERP_PARAMETERS(LAGRANGE_VARIABLE_TYPE)%PTR

          CALL FIELD_INTERPOLATION_PARAMETERS_ELEMENT_GET(FIELD_VALUES_SET_TYPE,ELEMENT_NUMBER, &
            & GEOMETRIC_INTERPOLATION_PARAMETERS,ERR,ERROR,*999)
          CALL FIELD_INTERPOLATION_PARAMETERS_ELEMENT_GET(FIELD_VALUES_SET_TYPE,ELEMENT_NUMBER, &
            & DEPENDENT_INTERPOLATION_PARAMETERS,ERR,ERROR,*999)

          !Point interpolation pointer
          GEOMETRIC_INTERPOLATED_POINT=>CONSTRAINT_EQUATIONS%INTERPOLATION%GEOMETRIC_INTERP_POINT(FIELD_U_VARIABLE_TYPE)%PTR
          GEOMETRIC_INTERPOLATED_POINT_METRICS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
            & GEOMETRIC_INTERP_POINT_METRICS(FIELD_U_VARIABLE_TYPE)%PTR
          DEPENDENT_INTERPOLATED_POINT=>CONSTRAINT_EQUATIONS%INTERPOLATION%DEPENDENT_INTERP_POINT(FIELD_VARIABLE_TYPE)%PTR
          DEPENDENT_INTERPOLATED_POINT_METRICS=>CONSTRAINT_EQUATIONS%INTERPOLATION% &
            & DEPENDENT_INTERP_POINT_METRICS(FIELD_VARIABLE_TYPE)%PTR


          !Loop over gauss points and add residuals
          DO gauss_idx=1,LAGRANGE_QUADRATURE_SCHEME%NUMBER_OF_GAUSS
            CALL FIELD_INTERPOLATE_GAUSS(FIRST_PART_DERIV,BASIS_DEFAULT_QUADRATURE_SCHEME,gauss_idx, &
              & GEOMETRIC_INTERPOLATED_POINT,ERR,ERROR,*999)
            CALL FIELD_INTERPOLATED_POINT_METRICS_CALCULATE(GEOMETRIC_BASIS%NUMBER_OF_XI,GEOMETRIC_INTERPOLATED_POINT_METRICS, &
              & ERR,ERROR,*999)
            CALL FIELD_INTERPOLATE_GAUSS(FIRST_PART_DERIV,BASIS_DEFAULT_QUADRATURE_SCHEME,gauss_idx, &
              & DEPENDENT_INTERPOLATED_POINT,ERR,ERROR,*999)
            CALL FIELD_INTERPOLATED_POINT_METRICS_CALCULATE(DEPENDENT_BASIS%NUMBER_OF_XI,DEPENDENT_INTERPOLATED_POINT_METRICS, &
              & ERR,ERROR,*999)
            
            RGW=(DEPENDENT_INTERPOLATED_POINT_METRICS%JACOBIAN-GEOMETRIC_INTERPOLATED_POINT_METRICS%JACOBIAN)* &
              & QUADRATURE_SCHEME%GAUSS_WEIGHTS(gauss_idx)

            element_dof_idx=0
            IF(LAGRANGE_VARIABLE%COMPONENTS(1)%INTERPOLATION_TYPE==FIELD_NODE_BASED_INTERPOLATION) THEN !node based
              DO parameter_idx=1,LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                element_dof_idx=element_dof_idx+1 
                NONLINEAR_MATRICES%ELEMENT_RESIDUAL%VECTOR(element_dof_idx)= &
                  & NONLINEAR_MATRICES%ELEMENT_RESIDUAL%VECTOR(element_dof_idx)+ &
                  & LAGRANGE_QUADRATURE_SCHEME%GAUSS_BASIS_FNS(parameter_idx,NO_PART_DERIV,gauss_idx)*RGW
              ENDDO
            ELSEIF(LAGRANGE_VARIABLE%COMPONENTS(mh)%INTERPOLATION_TYPE==FIELD_ELEMENT_BASED_INTERPOLATION) THEN !element based
              element_dof_idx=element_dof_idx+1 
              NONLINEAR_MATRICES%ELEMENT_RESIDUAL%VECTOR(element_dof_idx)= &
                & NONLINEAR_MATRICES%ELEMENT_RESIDUAL%VECTOR(element_dof_idx)+RGW
            ENDIF
          ENDDO !gauss_idx

          !Scale factor adjustment
          IF(LAGRANGE_FIELD%SCALINGS%SCALING_TYPE/=FIELD_NO_SCALING) THEN
            CALL FIELD_INTERPOLATION_PARAMETERS_SCALE_FACTORS_ELEM_GET(ELEMENT_NUMBER, &
              & LAGRANGE_INTERPOLATION_PARAMETERS,ERR,ERROR,*999) 
            element_dof_idx=0          
            IF(LAGRANGE_VARIABLE%COMPONENTS(1)%INTERPOLATION_TYPE==FIELD_NODE_BASED_INTERPOLATION) THEN !node based
              DO parameter_idx=1,LAGRANGE_BASIS%NUMBER_OF_ELEMENT_PARAMETERS
                element_dof_idx=element_dof_idx+1 
                NONLINEAR_MATRICES%ELEMENT_RESIDUAL%VECTOR(element_dof_idx)= &
                  & NONLINEAR_MATRICES%ELEMENT_RESIDUAL%VECTOR(element_dof_idx)* &
                  & LAGRANGE_INTERPOLATION_PARAMETERS%SCALE_FACTORS(parameter_idx,1)
              ENDDO
            ENDIF
          ENDIF
        CASE DEFAULT
          LOCAL_ERROR="Interface condition method "//TRIM(NUMBER_TO_VSTRING(CONSTRAINT_CONDITION%METHOD,"*",err,error))// &
            & " is not valid."
          CALL FLAG_ERROR(LOCAL_ERROR,ERR,ERROR,*999)
        END SELECT
      ELSE
        CALL FLAG_ERROR("Constraint condition equations is not associated.",ERR,ERROR,*999)
      ENDIF
    ELSE
      CALL FLAG_ERROR("Constraint condition is not associated.",ERR,ERROR,*999)
    ENDIF

    CALL EXITS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_RESIDUAL_EVALUATE")
    RETURN

999 CALL ERRORS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_RESIDUAL_EVALUATE",ERR,ERROR)
    CALL EXITS("FE_INCOMPRESSIBILITY_FINITE_ELEMENT_RESIDUAL_EVALUATE")
    RETURN 1
  END SUBROUTINE FE_INCOMPRESSIBILITY_FINITE_ELEMENT_RESIDUAL_EVALUATE

  !
  !================================================================================================================================
  !

END MODULE CONSTRAINT_OPERATORS_ROUTINES
